#!/usr/bin/env python3
"""
Check that every manifest the pilot reads exists, comes from the current generator and was generated from the
staged code (`cluster/prepare_data.sh` writes them; `cluster/pilot.sh` refuses to start a lane otherwise).

    python cluster/check_data.py            # exit 0 and one line per manifest, or exit 1 and what is wrong

A manifest is current when its ``generator_version`` is `pairs.manifest.GENERATOR_VERSION` and its generator code
commit is the code's own (`pairs.manifest.code_provenance`: the git commit, or on the cluster the commit
`cluster/stage.sh` recorded). Run from the repo root.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import List, Optional

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from pairs.manifest import GENERATOR_VERSION, code_provenance

MANIFESTS = (
    "data/demographic/credit/manifest.json",
    "data/demographic/cv/manifest.json",
    "data/demographic/education/asap2/manifest.json",
    "data/demographic/education/asap2_stage/manifest.json",
    "data/demographic/education_positioned/asap2_plausible/manifest.json",
    "data/demographic/education_positioned/asap2_implausible/manifest.json",
)


def problems(root: Path = Path("."), commit: Optional[str] = None) -> List[str]:
    """What is wrong with the manifests under ``root`` (empty = all current). ``commit`` is the code's commit
    (None: not checked, e.g. no provenance available)."""
    out = []
    for rel in MANIFESTS:
        path = root / rel
        if not path.is_file():
            out.append(f"{rel}: missing (run cluster/prepare_data.sh)")
            continue
        manifest = json.loads(path.read_text())
        version = manifest.get("generator_version")
        if version != GENERATOR_VERSION:
            out.append(f"{rel}: generator {version}, the code is {GENERATOR_VERSION} (rerun cluster/prepare_data.sh)")
        made_by = (manifest.get("code") or {}).get("git_commit")
        if commit is not None and made_by != commit:
            out.append(f"{rel}: generated by code {made_by}, the staged code is {commit} "
                       f"(rerun cluster/prepare_data.sh after staging)")
    return out


def main() -> None:
    commit = code_provenance().get("git_commit")
    found = problems(commit=commit)
    if found:
        print("data not ready:\n  " + "\n  ".join(found))
        sys.exit(1)
    print(f"data ready: {len(MANIFESTS)} manifests, generator {GENERATOR_VERSION}, code {commit}")


if __name__ == "__main__":
    main()
